### ISSUE TITLE
feat: 장바구니/결제 예외 처리 

### ISSUE THREAD

**Issue by min9120** [woowa-techcamp-2022/web-kiosk-gyeongminKim#20]
## ISSUE 개요🚀
메인 화면에서 장바구니/결제 시 예외 처리 또는 기능 추가할 부분 정리
- 목표
모두 구현!
## TODO ✅

- [ ] 이미 담겨있는 제품을 또 담았을때 해당 제품 카운트만 +1  (옵션이 다르다면 새로 추가) 
- [ ] 장바구니가 없는데 결제할 경우 '상품 선택 해주세요'
- [ ] 장바구니 제품 클릭하면 다시 옵션 변경 가능하도록 
- [ ] 장바구니 비우기 
- [ ] 장바구니 아이템 제거 
- [ ] 장바구니 추가
