### ISSUE TITLE
feat: 모달/ 상품 옵션 선택 콘텐츠 구현 

### ISSUE THREAD

**Issue by min9120** [woowa-techcamp-2022/web-kiosk-gyeongminKim#22]
## ISSUE 개요🚀
모달 창의 상품 옵션 선택 콘텐츠를 구현한다.
- 목표
상품 옵션 콘텐츠 내부 동작이 모두 정상 작동
## TODO ✅

- [x] 마크업 ( 옵션 선택 및 상품 설명 _가격, 등 ) 
- [x] 스타일링
- [x] 가로/세로 선택 
- [x] 엽서 템플릿 선택
~~타임 스탬프 선택~~ 
- [x] 수량 선택
- [ ] 장바구니 추가 
- [x] 모달 닫기
- [x] 취소
