### ISSUE TITLE
feat: 카드결제 구현 

### ISSUE THREAD

**Issue by min9120** [woowa-techcamp-2022/web-kiosk-gyeongminKim#26]
## ISSUE 개요🚀
카드 결제 시 요청 화면-> 랜덤한 시간-> 랜덤하게 에러 / 승인 -> 영수증 / 처음으로 
- 목표
카드 결제와 관련된 플로우를 모두 구현한다. 
## TODO ✅

- [x] 결제 요청 마크업 ( 애니메이션 ) 
- [x] 결제 랜덤 소요 시간 구현 
- [ ] 결제 에러 마크업 ( 주문 취소 (처음 페이지로 돌아갑니다)/ 다시 결제 ) 
- [x] 영수증 마크업
