### ISSUE TITLE
feat: 현금 결제 구현 

### ISSUE THREAD

**Issue by min9120** [woowa-techcamp-2022/web-kiosk-gyeongminKim#27]
## ISSUE 개요🚀
현금결제 -> 현금 선택 페이지-> 예외처리 -> 영수증 
- 목표
현금 결제와 관련된 모든 플로우를 구현한다. 
## TODO ✅

- [ ] 현금 선택 페이지 구현 
- [ ] 현금 선택 시 계산 로직 구현 
- [ ] 결제금액이 맞지 않을 시 예외처리 ( 너무 크거나 너무 작거나 ) 
- [ ] 결제 가능한 상태 유무를 UI 상에서 알려주기
