### ISSUE TITLE
feat: 추가 기능 

### ISSUE THREAD

**Issue by min9120** [woowa-techcamp-2022/web-kiosk-gyeongminKim#28]
## ISSUE 개요🚀

- 목표
어서 끝내고 추가 기능도 할 수 있기를! 
## TODO ✅

- [ ] 장바구니 추가 시 애니메이션 구현
- [ ] touch 이벤트 활용 
- [ ] 제품이 많을 경우 ( 20개 이상 ) 맨 하단에 맨 위로 올리기 버튼 구현 
- [ ] 장바구니 아이템이 많아서 스크롤이 될 때 버튼이 뜨면서 좌 우로 스크롤 대신 움직일 수 있다.
