### ISSUE TITLE
db: db 연결 

### ISSUE THREAD

**Issue by min9120** [woowa-techcamp-2022/web-kiosk-gyeongminKim#5]
## ISSUE 개요🚀
- 목표
~~typeORM을 사용해서 entity를 만들면 db 테이블이 생기는가?~~
db 모듈을 통해 creatConnection 하기

## TODO ✅

- [x] .env 환경 변수 설정
- [x]  typeORM 관련 셋팅 제거
- [x] database module 구현
